language: python

python:
  - 2.7

env:
  - PLONE_VERSION=4.3
#  - PLONE_VERSION=5.0
#  - PLONE_VERSION=5.1

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

before_install:
  - mkdir -p buildout-cache/{eggs,downloads}

install:
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - sed -ie "s#travis-4.3#travis-$PLONE_VERSION#" travis.cfg
  - python bootstrap.py --version=2.5.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg

script:
  - bin/test

after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
