# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          bin/test
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-build-coverage-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis src/collective/eeafaceted/batchactions
      - name: test coverage
        run: |
          coverage run bin/test
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
